/* Generated by Together */
package patrones.estructura.puente.modelos;

import javax.swing.table.AbstractTableModel;
import patrones.estructura.utilidades.Agenda;
import patrones.estructura.utilidades.Persona;

public class AgendaJTable extends AbstractTableModel {

    public AgendaJTable() {
        super();
    }

    @Override
    public Object getValueAt(int par1, int par2) {
        // Write your code here
        Persona p = (Persona) getAgenda().getPersonas().get(par1);
        if (par2 == 0) {
            return p.getNombre();
        } else {
            return p.getEmail();
        }
    }

    @Override
    public int getColumnCount() {
        // Write your code here
        return NOMBRES_DE_COLUMNAS.length;
    }

    @Override
    public int getRowCount() {
        // Write your code here
        return getAgenda().getPersonas().size();
    }

    public Agenda getAgenda() {
        return agenda;
    }

    @Override
    public String getColumnName(int i) {
        return NOMBRES_DE_COLUMNAS[i];
    }

    /**
     * @directed
     */
    private final Agenda agenda = Agenda.getInstancia();
    private final String[] NOMBRES_DE_COLUMNAS = {"Nombre", "Email"};
}
