/* Generated by Together */

package patrones.estructura.puente.modelos;

import javax.swing.AbstractListModel;
import patrones.estructura.utilidades.Agenda;

public class AgendaJList extends AbstractListModel {
    public AgendaJList() {
        super();
    }

    @Override
    public Object getElementAt(int par1) {
        // Write your code here
        return getAgenda().getPersonas().get(par1);
    }
@Override
    public int getSize() {
        // Write your code here
        return getAgenda().getPersonas().size();
    }

    public Agenda getAgenda() {
        return agenda;
    }

    /** @directed */
    private final Agenda agenda = Agenda.getInstancia();
}
