/* Generated by Together */

package patrones.estructura.mvc.biblioteca;

import patrones.creacion.constructor.categorias.Item;

public class Libro extends Item implements Comparable {
    public Libro(Tema tema, String nombre) {
        super(tema, nombre);
    }

    public String getIsbn() { return isbn; }

    public void setIsbn(String isbn) { this.isbn = isbn; }

    public int compareTo(Object par1) {
        // Write your code here
        return getIsbn().compareTo(((Libro)par1).getIsbn());
    }

    public String toString() {
        return getNombre();
    }

    private String isbn;
}
