/* Generated by Together */

package patrones.estructura.mvc.biblioteca;

import patrones.creacion.constructor.categorias.Categoria;

public class Tema extends Categoria implements Comparable {
    public Tema(String nombre) {
        super(nombre);
    }

    @Override
    public int compareTo(Object par1) {
        // Write your code here
        return getNombre().compareTo(((Tema)par1).getNombre());
    }

    @Override
    public String toString() {
        return getNombre();
    }

    /**
     * @clientCardinality 1
     * @supplierCardinality 0..*
     * @directed
     */
    private Libro lnkLibro;
}
