/* Generated by Together */

package patrones.estructura.ocultacion;

public class Ocultacion {
    public void operacion() {
        new SubsistemaA().operacionA();
        new SubsistemaB().operacionB();
    }

    /**
     * @link dependency
     * @stereotype instantiate
     */

    /*# SubsistemaB lnkSubsistemaB; */

    /**
     * @link dependency
     * @stereotype instantiate
     */

    /*# SubsistemaA lnkSubsistemaA; */
}
