/* Generated by Together */

package patrones.creacion.factoriaAbstracta;

class FactoriaCocina implements FactoriaMuebles {
    @Override
    public Mueble[] crearMuebles() {
        Mueble[] resultado = new MuebleImpl[3];
        resultado[0] = new MuebleImpl("Cocina");
        resultado[1] = new MuebleImpl("Horno microondas");
        resultado[2] = new MuebleImpl("Firgorífico");
        return resultado;
    }

    /**
     * @link
     * @shapeType PatternLink
     * @pattern AbstractFactory
     * @supplierRole Producto
     */

    /*# private MuebleImpl _muebleImpl; */
}
