/* Generated by Together */

package patrones.creacion.factoriaAbstracta;

public interface FactoriaMuebles {
    Mueble[] crearMuebles();

    /**
     * @link
     * @shapeType PatternLink
     * @pattern AbstractFactory
     * @clientRole Factoría
     * @supplierRole Producto
     */

    /*# private Mueble _mueble; */

    /**
     * @link
     * @shapeType PatternLink
     * @pattern AbstractFactory
     * @supplierRole Factoría Concreta
     */

    /*# private FactoriaCocina _factoriaCocina; */

    /**
     * @link
     * @shapeType PatternLink
     * @pattern AbstractFactory
     * @supplierRole Factoría Concreta
     */

    /*# private FactoriaSalon _factoriaSalon; */

    /**
     * @link
     * @shapeType PatternLink
     * @pattern AbstractFactory
     * @supplierRole Factoría Concreta
     */

    /*# private FactoriaDormitorio _factoriaDormitorio; */
}
