/* Generated by Together */

package patrones.creacion.factoriaAbstracta;

/** @testcase test.patrones.creacion.factoriaAbstracta.TestFactoriaAbstracta */
public class FactoriaAbstracta {
    public static FactoriaMuebles obtenerFactoria(int tipo) throws MuebleException {
        switch (tipo) {
            case COCINA:
                return new FactoriaCocina();
            case SALON:
                return new FactoriaSalon();
            case DORMITORIO:
                return new FactoriaDormitorio();
            default:
                throw new MuebleException("Tipo de habitación inesperado");
        }
    }

    public final static int COCINA = 0;
    public final static int SALON = 1;
    public final static int DORMITORIO = 2;

    /**
     * @link dependency
     * @stereotype instantiate
     */

    /*# MuebleException lnkMuebleException; */

    /** @link dependency */

    /*# FactoriaMuebles lnkFactoriaMuebles; */
}
