/* Generated by Together */

package patrones.creacion.factoriaAbstracta;

public interface Mueble {
    String getNombre();

    void setNombre(String nombre);

    String descripcion();

    /**
     * @link
     * @shapeType PatternLink
     * @pattern AbstractFactory
     * @supplierRole Factoría
     * @hidden
     */

    /*# private FactoriaMuebles _factoriaMuebles; */

    /**
     * @link
     * @shapeType PatternLink
     * @pattern AbstractFactory
     * @supplierRole Producto concreto
     */

    /*# private MuebleImpl _muebleImpl; */
}
