/* Generated by Together */

package patrones.creacion.factoriaAbstracta;

/** This exception is thrown when condition occurred */
public class MuebleException extends Exception {
    /** Constructs an Exception without a message. */
    public MuebleException() {
        super();
    }

    /**
     * Constructs an Exception with a detailed message.
     * @param message The message associated with the exception.
     */
    public MuebleException(String message) {
        super(message);
    }
}
