/* Generated by Together */
package patrones.estructura.puente.almacenamiento.operaciones;

public class OperacionJDBC implements Operacion {

    public OperacionJDBC(String ordenSQL) {
        this.delegado = ordenSQL;
    }

    @Override
    public int getTipo() {
        // Write your code here
        return 0;
    }

    @Override
    public void setTipo(int tipo) {
        // Write your code here
    }

    @Override
    public Object getDelegado() {
        return delegado;
    }

    @Override
    public void setDelegado(Object delegado) {
        this.delegado = delegado;
    }

    private Object delegado;
}
