/* Generated by Together */

package patrones.estructura.puente.almacenamiento.operaciones;

import java.io.Serializable;

public interface Operacion extends Serializable {
    int getTipo();

    void setTipo(int tipo);

    Object getDelegado();

    void setDelegado(Object delegado);

    int INSERTAR = 0;
    int MODIFICAR = 1;
    int MODIFICAR1 = 1;
    int CONSULTAR = 3;
}
