/* Generated by Together */
package patrones.estructura.puente.almacenamiento.operaciones;

public class OperacionArchivo implements Operacion {

    public OperacionArchivo(int tipo, Object delegado) {
        this.tipo = tipo;
        this.delegado = delegado;
    }

    @Override
    public int getTipo() {
        return tipo;
    }

    @Override
    public void setTipo(int tipo) {
        this.tipo = tipo;
    }

    /**
     *
     * @return
     */
    @Override
    public Object getDelegado() {
        return delegado;
    }

    @Override
    public void setDelegado(Object delegado) {
        this.delegado = delegado;
    }

    private int tipo;
    private Object delegado;
}
