/* Generated by Together */

package patrones.estructura.puente.iu;

import patrones.estructura.puente.modelos.AgendaJTable;
import javax.swing.JTable;

class PanelTabla extends PanelGeneral {
    /** Creates new form PanelLista */
    public PanelTabla() {
        super();
        mensaje.setText("Vista en formato tabla");
        modeloTabla = new AgendaJTable();
        tabla = new JTable(modeloTabla);
        scroll.getViewport().add(tabla);
    }

    /**
     * @directed
     * @clientCardinality 1
     * @supplierCardinality 1
     */
    private AgendaJTable modeloTabla;
    JTable tabla = null;
}
