/* Generated by Together */

package patrones.estructura.puente.iu;

import javax.swing.JList;
import patrones.estructura.puente.modelos.AgendaJList;

class PanelLista extends PanelGeneral {
    /** Creates new form PanelLista */
    public PanelLista() {
        super();
        mensaje.setText("Vista en formato lista");
        modeloLista = new AgendaJList();
        lista = new JList(modeloLista);
        scroll.getViewport().add(lista);
    }

    /**
     * @directed
     * @clientCardinality 1
     * @supplierCardinality 1
     */
    private AgendaJList modeloLista = null;
    JList lista = null;
}
