/* Generated by Together */

package patrones.estructura.puente.iu;

import javax.swing.JPanel;
import patrones.estructura.puente.modelos.AgendaJList;
import java.util.Collections;

public class Puente {
    public static JPanel obtenerPanel(int tipo) {
        if (tipo == LISTA) {
            PanelLista p = new PanelLista();
            AgendaJList modelo = (AgendaJList)p.lista.getModel();
            Collections.sort(modelo.getAgenda().getPersonas());
            return p;
        } else {
            return new PanelTabla();
        }
    }

    public final static int TABLA = 0;
    public final static int LISTA = 1;

    /** @link dependency */

    /*# PanelGeneral lnkPanelGeneral; */
}
