/* Generated by Together */

package patrones.creacion.prototipo;

public class UsoDeClone implements Cloneable {
    public UsoDeClone copiar() {
        try {
            return (UsoDeClone)this.clone();
        }
        catch (CloneNotSupportedException e) {
            e.printStackTrace();
            return null;
        }
    }

    public String getNombre() { return nombre; }

    public void setNombre(String nombre) { this.nombre = nombre; }

    private String nombre;
}
