/* Generated by Together */

package patrones.estructura.puente.almacenamiento.conexiones;

import java.util.Properties;

public class ConexionJDBC implements Conexion {
    public ConexionJDBC(String url, String driver, String usuario, String clave) {
        setUrl(url);
        setDriver(driver);
        setUsuario(usuario);
        setClave(clave);
    }

    public String getClave() { return clave; }

    public final void setClave(String clave) { this.clave = clave; }

    public String getUsuario() { return usuario; }

    public final void setUsuario(String usuario) { this.usuario = usuario; }

    public String getDriver() { return driver; }

    public final void setDriver(String driver) { this.driver = driver; }

    public String getUrl() { return url; }

    public final void setUrl(String url) { this.url = url; }

    public Properties datosConexion() {
        // Write your code here
        Properties p = new Properties();
        p.setProperty("url", getUrl());
        p.setProperty("driver", getDriver());
        p.setProperty("usuario", getUsuario());
        p.setProperty("clave", getClave());
        return p;
    }

    private String clave;
    private String usuario;
    private String driver;
    private String url;
}
