/* Generated by Together */

package patrones.estructura.puente.almacenamiento.almacenes;

import java.util.Iterator;
import patrones.estructura.puente.almacenamiento.conexiones.Conexion;
import patrones.estructura.puente.almacenamiento.operaciones.Operacion;
import patrones.estructura.puente.almacenamiento.operaciones.OperacionJDBC;
import java.util.Properties;

class AlmacenJDBC implements Almacen {
    public AlmacenJDBC(Conexion conexion) {
        abrir(conexion);
    }

    Implementador getImplementador() {
        return implementador;
    }

    void setImplementador(Implementador implementador) {
        this.implementador = implementador;
    }

    public final void abrir(Conexion fuente) {
        // Write your code here
        Properties p = fuente.datosConexion();
        String url = p.getProperty("url");
        String driver = p.getProperty("driver");
        String usuario = p.getProperty("usuario");
        String clave = p.getProperty("clave");
        setImplementador(new ImplementadorJDBC(url, driver, usuario, clave));
    }

    public void terminar() {
        // Write your code here
        getImplementador().terminar();
    }

    public Iterator ejecutar(Operacion objeto) {
        // Write your code here
        if (objeto instanceof OperacionJDBC) {
            return getImplementador().ejecutar(objeto);
        }
        return null;
    }

    private Implementador implementador;
}
