/* Generated by Together */

package patrones.creacion.factoria.interfaces;

class Coche implements Vehiculo {
    public Coche() { }

    @Override
    public String descripcion() {
        return "Marca: " + getMarca() + ". Precio: " + getPrecio() + ".Airbag: " + (isAirbag() ? "Sí" : "No");
    }

    public boolean isAirbag() { return airbag; }

    public void setAirbag(boolean airbag) { this.airbag = airbag; }

    public String getMarca() { return marca; }

    public void setMarca(String marca) { this.marca = marca; }

    public double getPrecio() { return precio; }

    public void setPrecio(double precio) { this.precio = precio; }

    /**
     * @link
     * @shapeType PatternLink
     * @pattern Factory Method
     * @supplierRole Creador
     * @hidden
     */

    /*# private FactoriaImpl _factoriaImpl; */

    private boolean airbag;
    private String marca;
    private double precio;
}
