/* Generated by Together */

package patrones.creacion.factoria.interfaces;

import patrones.creacion.factoria.herencia.VehiculoDesconocidoException;

public interface Factoria {
    Vehiculo obtenerVehiculo(int tipo) throws VehiculoDesconocidoException;

    /**
     * @link
     * @shapeType PatternLink
     * @pattern Factory Method
     * @clientRole Creador
     * @supplierRole Creado
     */

    /*# private Vehiculo _vehiculo; */

    /**
     * @link
     * @shapeType PatternLink
     * @pattern Factory Method
     * @supplierRole Creador concreto
     */

    /*# private FactoriaImpl _factoriaImpl; */

    int COCHE = 0;
    int MOTO = 1;

    /** @link dependency */

    /*# VehiculoDesconocidoException lnkVehiculoDesconocidoException; */

    /** @link dependency */

    /*# patrones.creacion.singleton.FactoriaSingleton lnkFactoriaSingleton; */
}
