/* Generated by Together */

package patrones.creacion.factoria.interfaces;

import patrones.creacion.factoria.herencia.VehiculoDesconocidoException;

public class FactoriaImpl implements Factoria {
    @Override
    public Vehiculo obtenerVehiculo(int tipo) throws VehiculoDesconocidoException {
        switch (tipo) {
            case Factoria.COCHE:
                return new Coche();
            case Factoria.MOTO:
                return new Moto();
            default:
                throw new VehiculoDesconocidoException("Tipo de vehículo desconocido");
        }
    }

    /**
     * @link
     * @shapeType PatternLink
     * @pattern Factory Method
     * @clientRole Creador
     * @supplierRole Creado
     */

    /*# private Coche _coche; */

    /** @link dependency */

    /*# patrones.creacion.factoria.herencia.VehiculoDesconocidoException lnkVehiculoDesconocidoException; */

    /**
     * @link
     * @shapeType PatternLink
     * @pattern Singleton
     * @supplierRole Factoria Singleton
     */

    /*# private patrones.creacion.singleton.FactoriaSingleton _factoriaSingleton; */
}
