/* Generated by Together */

package patrones.creacion.factoria.interfaces;

class Moto implements Vehiculo {
    public Moto() { }

    @Override
    public String descripcion() {
        return "Marca: " + getMarca() + ". Precio: " + getPrecio() + ".Tipo de motor: " + getTipoMotor() + " tiempos.";
    }

    public int getTipoMotor() { return tipoMotor; }

    public void setTipoMotor(int tipoMotor) { this.tipoMotor = tipoMotor; }

    public String getMarca() { return marca; }

    public void setMarca(String marca) { this.marca = marca; }

    public double getPrecio() { return precio; }

    public void setPrecio(double precio) { this.precio = precio; }

    /**
     * @link
     * @shapeType PatternLink
     * @pattern Factory Method
     * @supplierRole Creador
     * @hidden
     */

    /*# private FactoriaImpl _factoriaImpl; */

    private int tipoMotor;
    private String marca;
    private double precio;
}
