/* Generated by Together */

package patrones.estructura.compuesto;

import java.util.Enumeration;
import java.io.Serializable;
import java.util.Iterator;

public interface Empleado extends Serializable {
    double getSueldo();

    void setSueldo(double sueldo);

    Jefe getCompuesto();

    double obtenerSueldo();

    void nuevo(Empleado empleado);

    void eliminar(Empleado empleado);

    Iterator<Empleado> empleados();

    /**
     * @link
     * @shapeType PatternLink
     * @pattern Composite
     * @supplierRole Simple
     */

/*# private Subordinado _subordinado; */

    /**
     * @link
     * @shapeType PatternLink
     * @pattern Composite
     * @supplierRole Compuesto
     */

/*# private Jefe _jefe; */
}
