/* Generated by Together */
package patrones.estructura.compuesto;

import java.util.Iterator;

public class Subordinado implements Empleado {

    @Override
    public Jefe getCompuesto() {
        // Write your code here
        return null;
    }

    @Override
    public double obtenerSueldo() {
        // Write your code here
        return getSueldo();
    }

    @Override
    public void nuevo(Empleado empleado) {
        // Write your code here
    }

    @Override
    public void eliminar(Empleado empleado) {
        // Write your code here
    }

    @Override
    public Iterator<Empleado> empleados() {
        // Write your code here
        return null;
    }

    @Override
    public double getSueldo() {
        return sueldo;
    }

    @Override
    public void setSueldo(double sueldo) {
        this.sueldo = sueldo;
    }

    private double sueldo;
}
