/* Generated by Together */

package patrones.estructura.mvc.modelos;

import javax.swing.AbstractListModel;
import patrones.estructura.mvc.biblioteca.Catalogo;
import patrones.estructura.mvc.biblioteca.Tema;
import patrones.estructura.mvc.biblioteca.Libro;

public class ModeloCatalogoJList extends AbstractListModel {
    public ModeloCatalogoJList() {
        super();
        rellenarCatalogo();
    }

    @Override
    public Object getElementAt(int par1) {
        // Write your code here
        return Catalogo.getInstancia().getTemas().get(par1);
    }
@Override
    public int getSize() {
        // Write your code here
        return Catalogo.getInstancia().getTemas().size();
    }

    private void rellenarCatalogo() {
        // message #1.1 to tema:patrones.estructura.mvc.biblioteca.Tema
        Tema tema = new Tema("Java");
        // message #1.2 to libro1:patrones.estructura.mvc.biblioteca.Libro
        Libro libro1 = new Libro(tema, "Lenguajes de programación");
        libro1.setIsbn("123");
        // message #1.3 to tema:patrones.estructura.mvc.biblioteca.Tema
        tema.nuevoItem(libro1);
        libro1 = new Libro(tema, "Java avanzado");
        libro1.setIsbn("456");
        tema.nuevoItem(libro1);
        libro1 = new Libro(tema, "Java con base de datos");
        libro1.setIsbn("789");
        tema.nuevoItem(libro1);
        Catalogo.getInstancia().getTemas().add(tema);
        tema = new Tema("Literatura española");
        libro1 = new Libro(tema, "El Quijote");
        tema.nuevoItem(libro1);
        libro1 = new Libro(tema, "La casa de Bernarda Alba");
        tema.nuevoItem(libro1);
        Catalogo.getInstancia().getTemas().add(tema);
    }

    /** @link dependency */

    /*# patrones.estructura.mvc.biblioteca.Catalogo lnkCatalogo; */

    /** @link dependency */

    /*# patrones.estructura.mvc.biblioteca.Libro lnkLibro; */

    /** @link dependency */

    /*# patrones.estructura.mvc.biblioteca.Tema lnkTema; */
}
