/* Generated by Together */

package patrones.estructura.mvc.modelos;

import javax.swing.table.AbstractTableModel;
import patrones.estructura.mvc.biblioteca.Catalogo;
import patrones.estructura.mvc.biblioteca.Tema;
import patrones.estructura.mvc.biblioteca.Libro;

public class ModeloCatalogoJTable extends AbstractTableModel {
    public ModeloCatalogoJTable() {
        super();
    }
@Override
    public Object getValueAt(int par1, int par2) {
        // Write your code here
        Tema tema = (Tema)Catalogo.getInstancia().getTemas().get(0);
        if (par2 == 0) { //Se solicita un tema
            return tema.getNombre();
        }
        else {
            Libro libro = (Libro)tema.getItems().get(par1);
            switch (par2) {
                case 1:
                    return libro.getNombre();
                case 2:
                    return libro.getIsbn();
                default:
                    return true;
            }
        }
    }
@Override
    public int getColumnCount() {
        // Write your code here
        return NOMBRES_DE_COLUMNAS.length;
    }
@Override
    public int getRowCount() {
        // Write your code here
        Tema tema = (Tema)Catalogo.getInstancia().getTemas().get(0);
        return tema.nItems();
    }
@Override
    public boolean isCellEditable(int i, int i1) {
        return false;
    }
@Override
    public String getColumnName(int i) {
        return NOMBRES_DE_COLUMNAS[i];
    }
@Override
    public Class getColumnClass(int i) {
        if (i < getColumnCount() - 1) {
            return String.class;
        } else {
            return Boolean.class;
        }
    }

    private static final String[] NOMBRES_DE_COLUMNAS = {"Tema","Título","Isbn","Disponible"};

    /** @link dependency */

    /*# Catalogo lnkCatalogo; */

    /** @link dependency */

    /*# Tema lnkTema; */

    /** @link dependency */

    /*# Libro lnkLibro; */
}
