/* Generated by Together */

package patrones.creacion.constructor.iu;

import patrones.creacion.constructor.categorias.Categoria;

public class Constructor implements Factoria {
    protected Constructor() { }

    @Override
    public MultiPanel obtenerPanel(Categoria categoria) {
        // Write your code here
        if (categoria.nItems() > MAX_ITEMS) {
            return new CreadorPanelLista().obtenerPanel(categoria);
        } else {
            return new CreadorPanelCheckBox().obtenerPanel(categoria);
        }
    }

    public static Constructor getInstancia() {
        synchronized(patrones.creacion.constructor.iu.Constructor.class) {
            if (instancia == null) {
                instancia = new patrones.creacion.constructor.iu.Constructor();
            }
        }
        return instancia;
    }

    private final static int MAX_ITEMS = 3;

    /**
     * @link
     * @shapeType PatternLink
     * @pattern Singleton
     * @supplierRole Factoría Singleton
     */

    /*# private Constructor _constructor; */

    private static Constructor instancia = null;
}
