/* Generated by Together */

package patrones.creacion.constructor.iu;

import patrones.creacion.constructor.categorias.Categoria;

class CreadorPanelLista implements Factoria {
    @Override
    public MultiPanel obtenerPanel(Categoria categoria) {
        return new PanelLista(categoria);
    }
}
