/* Generated by Together */

package patrones.creacion.constructor.iu;

import patrones.creacion.constructor.categorias.Categoria;

class CreadorPanelCheckBox implements Factoria {
    @Override
    public MultiPanel obtenerPanel(Categoria categoria) {
        return new PanelCheckBox(categoria);
    }
}
