/* Generated by Together */

package patrones.creacion.constructor.iu;

import patrones.creacion.constructor.categorias.Categoria;

public interface Factoria {
    MultiPanel obtenerPanel(Categoria categoria);

    /**
     * @link
     * @shapeType PatternLink
     * @pattern Factory Method
     * @clientRole Creador
     * @supplierRole Producto
     */

    /*# private MultiPanel _multiPanel; */

    /**
     * @link
     * @shapeType PatternLink
     * @pattern Factory Method
     * @supplierRole Creador Concreto
     */

    /*# private CreadorPanelLista _creadorpanelLista; */

    /**
     * @link
     * @shapeType PatternLink
     * @pattern Factory Method
     * @supplierRole Creador Concreto
     */

    /*# private CreadorPanelCheckBox _creadorPanelCheckBox; */
}
