/* Generated by Together */

package patrones.creacion.constructor.iu;

import java.awt.Panel;

public interface MultiPanel {
    Panel panelVisual();

    /**
     * @link
     * @shapeType PatternLink
     * @pattern Factory Method
     * @supplierRole Creador
     * @hidden
     */

    /*# private Factoria _factoria; */

    /**
     * @link
     * @shapeType PatternLink
     * @pattern Factory Method
     * @supplierRole Producto Concreto
     */

    /*# private PanelLista _panelLista; */

    /**
     * @link
     * @shapeType PatternLink
     * @pattern Factory Method
     * @supplierRole Producto Concreto
     */

    /*# private PanelCheckBox _panelCheckBox; */
}
