/* Generated by Together */

package patrones.creacion.constructor.iu;

import patrones.creacion.constructor.categorias.Categoria;
import patrones.creacion.constructor.categorias.Item;
import java.awt.Panel;
import java.awt.BorderLayout;
import java.awt.HeadlessException;
import java.awt.Label;
import java.awt.List;
import java.util.Iterator;

class PanelLista extends Panel implements MultiPanel {
    public PanelLista(Categoria categoria) {
        this.categoria=categoria;
        init(categoria);
    }

    private void init(Categoria categoria1) throws HeadlessException {
        setLayout(new BorderLayout());
        add(new Label(getCategoria().getNombre()), BorderLayout.NORTH);
        List l = new List();
        l.setMultipleMode(true);
        add(l, BorderLayout.CENTER);
        for (Iterator<Item> e = categoria1.iterador(); e.hasNext();) {
            Item item = e.next();
            l.add(item.getNombre());
        }
    }

    @Override
    public Panel panelVisual() {
        // Write your code here
        return this;
    }

    public Categoria getCategoria() { return categoria; }

    public void setCategoria(Categoria categoria) { this.categoria = categoria; }

    private Categoria categoria;
}
