/* Generated by Together */

package patrones.creacion.constructor.iu;

import patrones.creacion.constructor.categorias.Categoria;
import patrones.creacion.constructor.categorias.Item;
import java.awt.Panel;
import java.awt.GridLayout;
import java.awt.Label;
import java.awt.Checkbox;
import java.awt.HeadlessException;
import java.util.Iterator;

class PanelCheckBox extends Panel implements MultiPanel {
    public PanelCheckBox(Categoria categoria) {
        this.categoria=categoria;
        
        init(categoria);
    }

    private void init(Categoria categoria1) throws HeadlessException {
        setLayout(new GridLayout(0, 1));
        add(new Label(getCategoria().getNombre()));
        for (Iterator<Item> e = categoria1.iterador(); e.hasNext();) {
            Item item = e.next();
            add(new Checkbox(item.getNombre()));
        }
    }

    @Override
    public Panel panelVisual() {
        // Write your code here
        return this;
    }

    public Categoria getCategoria() { return categoria; }

    public void setCategoria(Categoria categoria) { this.categoria = categoria; }

    private Categoria categoria;
}
