/* Generated by Together */

package patrones.estructura.estetico;

import javax.swing.JComponent;
import java.awt.BorderLayout;

public class Decorador extends JComponent {
    public Decorador(JComponent c) {
        super();
        init(c);
    }

    private void init(JComponent c) {
        setLayout(new BorderLayout());
        add(c, BorderLayout.CENTER);
    }
    
}
