/* Generated by Together */

package patrones.estructura.estetico;

import javax.swing.JComponent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.Graphics;
import java.awt.Dimension;
import java.awt.Color;

public class DecoradorJButton extends Decorador {
    public DecoradorJButton(JComponent c) {
        super(c);
        c.addMouseListener(
            new MouseAdapter() {
                @Override
                public void mouseEntered(MouseEvent e) {
                    dentro = true;
                    repaint();
                }
                @Override
                public void mouseExited(MouseEvent e) {
                    dentro = false;
                    repaint();
                }
            });
    }

    @Override
    public void paint(Graphics graphics) {
        super.paint(graphics);
        if (!dentro) {
            Dimension d = super.getSize();
            graphics.setColor(Color.lightGray);
            graphics.drawRect(0, 0, d.width - 1, d.height - 1);
            graphics.drawLine(d.width - 2, 0, d.width - 2, d.height - 1);
            graphics.drawLine(0, d.height - 2, d.width - 2, d.height - 2);
        }
    }

    private boolean dentro;
}
