/* Generated by Together */

package patrones.estructura.mvc.vistas;

import javax.swing.JList;
import patrones.estructura.mvc.modelos.ModeloCatalogoJList;

public class VistaCatalogoJList extends JList {
    public VistaCatalogoJList() {
        super(new ModeloCatalogoJList());
    }

    /** @link dependency */

/*# patrones.estructura.mvc.biblioteca.Catalogo lnkCatalogo; */

    /** @link dependency */

/*# ModeloCatalogoJList lnkModeloCatalogo; */
}
