/* Generated by Together */

package patrones.estructura.mvc.vistas;

import javax.swing.JTable;
import patrones.estructura.mvc.modelos.ModeloCatalogoJTable;

public class VistaCatalogoJTable extends JTable {
    public VistaCatalogoJTable() {
        super(new ModeloCatalogoJTable());
    }

    /** @link dependency */

/*# ModeloCatalogoJTable lnkModeloCatalogoJTable; */
}
