/* Generated by Together */

package patrones.comportamiento.cadenaderesponsabilidad;

import java.util.EventObject;

public class Evento1 extends EventObject {
    public Evento1(Object par1) {
        super(par1);
    }
}
