/* Generated by Together */

package patrones.comportamiento.cadenaderesponsabilidad;

import java.util.EventObject;

public class Evento2 extends EventObject {
    public Evento2(Object par1) {
        super(par1);
    }
}
