/* Generated by Together */

package patrones.comportamiento.cadenaderesponsabilidad;

import java.util.EventObject;

public class Manejador {
    public void manejarPeticion(EventObject suceso) {
        if (siguientemanejador != null) {
            siguientemanejador.manejarPeticion(suceso);
        }
        // Write your code here
        System.out.println("Ejecutando 'manejadorPeticion()' de la clase " + this.getClass().getName());
    }

    public void setSiguientemanejador(Manejador siguientemanejador) {
        this.siguientemanejador = siguientemanejador;
    }

    public Manejador getSiguientemanejador() {
        return siguientemanejador;
    }

    /** @link aggregation */
    private Manejador siguientemanejador;
}
