/* Generated by Together */

package patrones.comportamiento.cadenaderesponsabilidad;

import java.util.EventObject;

public class ManejadorConcreto2 extends Manejador {
    @Override
    public void manejarPeticion(EventObject suceso) {
        if (suceso instanceof Evento2) {
            System.out.println("Ejecutando 'manejadorPeticion()' de la clase " + this.getClass().getName());
            System.out.println("Suceso de tipo: " + suceso.getClass().getName());
        }
        else if (getSiguientemanejador() != null) {
            getSiguientemanejador().manejarPeticion(suceso);
        }
    }
}
