/* Generated by Together */

package patrones.estructura.adaptador;

import java.util.ArrayList;
import javax.swing.event.TableModelListener;
import patrones.estructura.utilidades.Persona;
import patrones.estructura.utilidades.Agenda;

public class AdaptadorAgenda implements Modelo {
    public AdaptadorAgenda(Agenda agenda) {        
        this.listeners = new ArrayList<>();
        this.agenda = agenda;
    }

    @Override
    public int getRowCount() {
        // Write your code here
        return agenda.getPersonas().size();
    }

    @Override
    public int getColumnCount() {
        // Write your code here
        return NOMBRES_DE_COLUMNAS.length;
    }

    @Override
    public String getColumnName(int par1) {
        // Write your code here
        return NOMBRES_DE_COLUMNAS[par1];
    }

    @Override
    public Class getColumnClass(int par1) {
        // Write your code here
        return String.class;
    }

    @Override
    public boolean isCellEditable(int par1, int par2) {
        // Write your code here
        return false;
    }

    @Override
    public Object getValueAt(int par1, int par2) {
        // Write your code here
        Persona p = (Persona)agenda.getPersonas().get(par1);
        if (par2 == 0) {
            return p.getNombre();
        } else {
            return p.getEmail();
        }
    }

    @Override
    public void setValueAt(Object par1, int par2, int par3) {
        // Write your code here
    }
@Override
    public void addTableModelListener(TableModelListener par1) {
        // Write your code here
        listeners.add(par1);
    }
@Override
    public void removeTableModelListener(TableModelListener par1) {
        // Write your code here
        listeners.remove(par1);
    }

    private final Agenda agenda;


    private final ArrayList<TableModelListener> listeners;
    private final static String[] NOMBRES_DE_COLUMNAS = {"Nombre","Correo electrónico"};
}
