/* Generated by Together */

package patrones.estructura.adaptador;

import javax.swing.table.TableModel;

public interface Modelo extends TableModel {
    /**
     * @link
     * @shapeType PatternLink
     * @pattern Adapter
     * @clientRole <{Modelo}>
     * @supplierRole Adaptador
     */

    /*# private AdaptadorAgenda _adaptadorAgenda; */
}
