/* Generated by Together */

package patrones.creacion.constructor.categorias;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

public class Categoria {
    public Categoria(String nombre) {
        this.nombre = nombre;
    }

    public String getNombre() { return nombre; }

    public void setNombre(String nombre) { this.nombre = nombre; }

    public List<Item> getItems() {
        if (items == null) {
            items = new ArrayList<>();
        }
        return items;
    }

    public int nItems() {
        return getItems().size();
    }

    public void nuevoItem(Item nuevo) {
        getItems().add(nuevo);
    }

    public Iterator<Item> iterador() {
        return getItems().iterator();
    }

    private String nombre;

    /**
     *@link aggregation
     *@associates <{Item}>
     * @bidirectional <{patrones.creacion.constructor.categorias.Item#lnkrevCategoria}>
     */
    private List<Item> items;
}
