/* Generated by Together */

package patrones.creacion.constructor.categorias;

public class Item {
    public Item(Categoria categoria, String nombre) {
        this.categoria = categoria;
        this.nombre=nombre;
    }

    public String getNombre() { return nombre; }

    public void setNombre(String nombre) { this.nombre = nombre; }

    public Categoria getCategoria() {
        return categoria;
    }

    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }

    private String nombre;

    /** @bidirectional */
    private Categoria categoria;
}
