/* Generated by Together */

package patrones.comportamiento.interprete;

/** This exception is thrown when condition occurred */
public class InterpreteException extends Exception {
    /** Constructs an Exception without a message. */
    public InterpreteException() {
        super();
    }

    /**
     * Constructs an Exception with a detailed message.
     * @param message The message associated with the exception.
     */
    public InterpreteException(String message) {
        super(message);
    }
}
