/* Generated by Together */

package patrones.comportamiento.interprete;

import java.util.Properties;

public class Orden1 implements Orden {
    public Orden1() {
        this.siguiente = new Orden2();
    }

    @Override
    public boolean ejecutar(Properties parametros) throws InterpreteException {
        // Write your code here
        if (parametros.getProperty("NOMBRE").equals("ORDEN1")) {
            System.out.println("Orden 1 ejecutada.");
            return true;
        } else if (getSiguiente() != null) {
            return getSiguiente().ejecutar(parametros);
        }
        else {
            throw new InterpreteException("Orden desconocida");
        }
    }

    @Override
    public Orden getSiguiente() { return siguiente; }

    @Override
    public void setSiguiente(Orden siguiente) { this.siguiente = siguiente; }

    private Orden siguiente;
}
