/* Generated by Together */

package patrones.comportamiento.interprete;

import java.util.Properties;

public interface Orden {
    boolean ejecutar(Properties parametros) throws InterpreteException;

    Orden getSiguiente();

    void setSiguiente(Orden siguiente);
}
