/* Generated by Together */

package patrones.comportamiento.interprete;

import java.util.Properties;

public class Orden3 implements Orden {
    public Orden3() {
        this.siguiente = null;
    }

    @Override
    public boolean ejecutar(Properties parametros) throws InterpreteException {
        // Write your code here
        if (parametros.getProperty("NOMBRE").equals("ORDEN3")) {
            System.out.println("Fin del programa.");
            return false;
        } else if (getSiguiente() != null) {
            return getSiguiente().ejecutar(parametros);
        }
        else {
            throw new InterpreteException("Orden desconocida");
        }
    }

    @Override
    public Orden getSiguiente() { return siguiente; }

    @Override
    public void setSiguiente(Orden siguiente) { this.siguiente = siguiente; }

    private Orden siguiente;
}
