/* Generated by Together */

package patrones.comportamiento.interprete;

public class TestInterprete {
    public TestInterprete() {
        this.interprete = new Interprete();
    }

    public static void main(String[] argv) {
        new TestInterprete().getInterprete().buclePrincipal();
    }

    public Interprete getInterprete() { return interprete; }

    public void setInterprete(Interprete interprete) { this.interprete = interprete; }

    private Interprete interprete;
}
