/* Generated by Together */

package patrones.creacion.factoria.herencia;

class Coche extends Vehiculo {
    public boolean isAirbag() { return airbag; }

    public void setAirbag(boolean airbag) { this.airbag = airbag; }

    @Override
    public String descripcion() {
        return super.descripcion() + " Airbag: " + (isAirbag() ? "Sí" : "No");
    }

    private boolean airbag;
}
