/* Generated by Together */

package patrones.creacion.factoria.herencia;


public class FactoriaHerencia {
    public static void main(String[] args) {
        System.out.println("Ejemplo de uso del patrón factoría implementado usando herencia");
        ejecutarPatron();
        System.out.println("Fin ejemplo de uso del patrón factoría implementado usando herencia");
    }

    public static void ejecutarPatron() {
        try {
            // message #1.1 to f:patrones.creacion.factoria.herencia.Factoria
            Vehiculo vehiculo = Factoria.obtenerVehiculo(Factoria.COCHE);
            System.out.println(vehiculo.descripcion());
        }
        catch (VehiculoDesconocidoException e) {
            e.printStackTrace();
        }
    }
}
