/* Generated by Together */

package patrones.creacion.factoria.herencia;

public class Factoria {
    public static final Vehiculo obtenerVehiculo(final int tipo) throws VehiculoDesconocidoException {
        Vehiculo v = null;
        switch (tipo) {
            case COCHE:
                v = new Coche();
                break;
            case MOTO:
                v = new Moto();
                break;
            default:
                throw new VehiculoDesconocidoException("Tipo de Vehículo inesperado: " + tipo);
        }
        return v;
    }

    public final static int COCHE = 0;
    public final static int MOTO = 1;

    /**
     * @link dependency
     * @stereotype instantiate
     */

    /*# Vehiculo lnkVehiculo; */

    /**
     * @link dependency
     * @stereotype instantiate
     */

    /*# VehiculoDesconocidoException lnkVehiculoNoSoportadoException; */
}
