/* Generated by Together */

package patrones.creacion.factoria.herencia;

/** This exception is thrown when condition occurred */
public class VehiculoDesconocidoException extends Exception {
    /** Constructs an Exception without a message. */
    public VehiculoDesconocidoException() {
        super();
    }

    /**
     * Constructs an Exception with a detailed message.
     * @param message The message associated with the exception.
     */
    public VehiculoDesconocidoException(String message) {
        super(message);
    }
}
