/* Generated by Together */

package patrones.creacion.factoria.herencia;

abstract public class Vehiculo {
    public double getPrecio() { return precio; }

    public void setPrecio(double precio) { this.precio = precio; }

    public String getMarca() { return marca; }

    public void setMarca(String marca) { this.marca = marca; }

    public String descripcion() {
        return "Marca: " + getMarca() + ". Precio: " + getPrecio();
    }

    private double precio;
    private String marca;
}
